version: '3.7'

services: 
    blogengine:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./blogengine:/blogengine
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1
            - SECRET_KEY=samplesecretkey123
            - ALLOWED_HOSTS=0.0.0.0